name: ready-bedrock

services:
  mc-server:
    build:
      context: .
      dockerfile: base.docker
    container_name: mc-bedrock-production
    ports:
      - "19132:19132/udp"
    volumes:
      - ./worlds:/data/worlds
      - ./server.properties:/data/server.properties
      - ./backups:/data/backups
    environment:
      - UID=10001
      - GID=10001
      - EULA=TRUE
      - ONLINE_MODE=true
      - ALLOW_CHEATS=false
      - SERVER_NAME=我的正式伺服器
      - MAX_PLAYERS=20
      - DIFFICULTY=hard
      - LEVEL_NAME=Prod_World
      - AUTO_LEVEL_CREATE=true

      # 秒啟動優化
      - VERSION=1.26.3.1
      - SKIP_DOWNLOAD_COMPARE=true
      - SKIP_BACKUP=true

      - ALLOW_LIST=false

    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'